export enum ClaimJourneyState {
  CASE_SELECTION_INCOMPLETE = "CASE_SELECTION_INCOMPLETE",
  CLAIM_TYPE_INCOMPLETE = "CLAIM_TYPE_INCOMPLETE",
  CLAIM_SUBTYPE_INCOMPLETE = "CLAIM_SUBTYPE_INCOMPLETE",
  TOTAL_COST_INCOMPLETE = "TOTAL_COST_INCOMPLETE",
  EVIDENCE_INCOMPLETE = "EVIDENCE_INCOMPLETE",
  COMPLETE = "COMPLETE",
}
